### ISSUE TITLE
Not a PyPI package

### ISSUE THREAD

**Issue by charmoniumQ** [jol-jol/pymatlabparser#2]
This work has potential but is of limited use, since this work itself is not a PyPI package (although `sly` is). One has to copy/paste it in to their project which does not give credit to the original author nor does it permit updates to newer versions.

I will help you package this with poetry if you wish.

**Comment by jol-jol** [comment]
Hi there, thanks a lot for your interest! This was more of a side project when I was attending university, so it hasn't been rigorously tested. I guess it's probably not suitable to be shared on public platforms because of that. But feel free to fork or just copy to your own repo, improve, test and publish it, if you'd like. MATLAB is has very interesting syntax.

**Comment by charmoniumQ** [comment]
Thanks for the response :+1:
